### ISSUE TITLE
Manejo de hover en React que podría ser CSS

### ISSUE THREAD

**Issue by chanagaray** [MarianoRamborger/Lanera#1]
Hola, Marian, tanto tiempo. Me aparecen los nuevos repos en el feed así que estuve stalkeando el código un poquito. Capaz te sirve esto: 

En vez de manejar un estado dependiente de onMouseEnter y onMouseLeave con javascript, podrías directamente tener dos selectores de CSS para el elemento que querés ocultar. Sería algo como:

```css
.elemento > .elementoHijo {
    /* Los estilos normales del elemento */
}

.elemento:hover >.elementoHijo {
    display: none;
}
```
Inclusive, si quisieras hacerlo más fancy podrías hacer que tenga un `height: 0;` en el hover y usar una transición con `transition: height 1s;`.

¡Abrazo!

https://github.com/MarianoRamborger/Lanera/blob/2329899c81d2ffb215c3e9c9b6b46032fdafaada/src/Header/Navbar/Navbar.js#L48
